# Clean React Native Android Build Script
workflows:
  react-native-android:
    name: React Native Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: | 
          npm install --force
      - name: Build Android APK
        script: | 
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com # Put your email here to get the APK
          
