# React Native Android Build Script (Direct)
workflows:
  react-native-android:
    name: React Native Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
    scripts:
      - name: Install dependencies and build
        script: | 
          npm install --force
          ./gradlew -p template/android assembleRelease -x lint
    artifacts:
      - 'template/android/app/build/outputs/apk/**/*.apk'
    publishing:
      email:
        recipients:
          - your-email@example.com # Put your email here
          
