# Clean React Native Android Build Script (Verified Path)
workflows:
  react-native-android:
    name: React Native Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
    scripts:
      - name: Install dependencies and build
        script: | 
          npm install --force
          if [ -d "template/android" ]; then
            cd template/android
          elif [ -d "android" ]; then
            cd android
          else
            echo "Android directory not found!"
            exit 1
          fi
          ./gradlew assembleRelease -x lint -g $(pwd)/.gradle
    artifacts:
      - '**/app/build/outputs/apk/**/*.apk'
    publishing:
      email:
        recipients:
          - your-email@example.com # Put your email here
          
