workflows:
  flutter-app:
    name: Build Taptitan Game
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      # --- YOUR SDKs STAY ABOVE OR HERE ---
      # (Don't change your existing SDK/Environment blocks)

    scripts:
      - name: Clean and Get Packages (Auto-Locate Fix)
        script: |
          # This command finds your project folder even if it's nested
          PROJECT_PATH=$(find . -name "pubspec.yaml" -print -quit | xargs dirname)
          cd "$PROJECT_PATH"
          
          echo "Found project at: $(pwd)"
          
          # Now it runs your commands inside the right folder
          flutter clean
          flutter pub get

      - name: Build APK (Auto-Locate Fix)
        script: |
          PROJECT_PATH=$(find . -name "pubspec.yaml" -print -quit | xargs dirname)
          cd "$PROJECT_PATH"
          
          flutter build apk --release
          
    artifacts:
      - build/**/outputs/**/*.apk
      
