workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials # Only if you have signing keys set up in Codemagic UI
      vars:
        PACKAGE_NAME: "taptitan" # Change this to your package name
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build APK for release
        script: | 
          flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@elvinezimov1996gmail.com # Put your email here to get the file when it's done
          
