workflows:
  android-template-build:
    name: Android Template Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    # This points CodeMagic to the right starting line
    working_directory: template/android 
    environment:
      groups:
        - keystore_credentials # Ensure these match your CodeMagic UI settings
      vars:
        PACKAGE_NAME: "com.your.package"
    scripts:
      - name: Install dependencies
        script: | 
          ./gradlew dependencies
      - name: Build Android APK
        script: | 
          # We are already inside template/android, so we run gradlew directly
          ./gradlew assembleRelease
    artifacts:
      # We look inside the current working directory for the output
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - your-elvinezimov1996@gmail.com
          
