scripts:
  - name: Clean and Get Packages
    script: |
      # --- KEEPING YOUR SDKs EXACTLY THE SAME ---
      # (Existing SDK code stays above this)

      # --- THE BYPASS FIX ---
      # This finds your project folder automatically so 'clean' doesn't fail
      PROJECT_ROOT=$(find . -name "pubspec.yaml" -exec dirname {} \;)
      cd $PROJECT_ROOT
      
      echo "Currently in: $(pwd)"
      
      flutter clean
      flutter pub get

  - name: Build APK
    script: |
      PROJECT_ROOT=$(find . -name "pubspec.yaml" -exec dirname {} \;)
      cd $PROJECT_ROOT
      flutter build apk --release
      
