workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest # Only if you're using a Mac instance
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Get Flutter dependencies
        script: | 
          flutter packages pub get
      - name: Fix Gradle permissions
        script: | 
          # This fixes the common 'permission denied' error for gradlew
          chmod +x android/gradlew
      - name: Build Android APK
        script: | 
          # Using the wrapper directly ensures consistency
          cd android && ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
          
