# Clean React Native Android Build Script (Bypassing checks)
workflows:
  react-native-android:
    name: React Native Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
    scripts:
      - name: Install dependencies and build
        script: | 
          npm install --force
          cd android && ./gradlew assembleRelease -x lint -g $(pwd)/.gradle
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com # Put your email here to get the APK
          
